main:
  project_name: weather-prediction
  experiment_name: production
  steps: all
data_ingestion:
  hostname: archive-api.open-meteo.com
data_check:
  kl_threshold: 0.3
data_segregation:
  # Fraction of data to use for test (the remaining will be used for train and validation)
  test_size: 0.3
modeling:
  # Fraction of remaining data to use for validation
  val_size: 0.3
  XGBRegressor:
    learning_rate: 0.095
    max_depth: 9
    subsample: 0.95
    n_estimators: 150
    gamma: 0.3
    reg_alpha: 0.43
  RandomForestClassifier:
    min_samples_split: 2
    min_samples_leaf: 1
    n_estimators: 325
    criterion: 'gini'
    max_features: 'sqrt'
    bootstrap: True
cities:
  Berlin:
    id: 1
    latitude: 52.5244
    longitude: 13.4105
  Munich:
    id: 2
    latitude: 48.1374
    longitude: 11.5755
  Hamburg:
    id: 3
    latitude: 53.5507
    longitude: 9.993
  Frankfurt:
    id: 4
    latitude: 50.1155
    longitude: 8.6842
  Cologne:
    id: 5
    latitude: 50.9333
    longitude: 6.95